package com.agent.tool;

public enum ToolErrorCode {
    WORKSPACE_VIOLATION,
    FILE_NOT_FOUND,
    ACCESS_DENIED,
    INVALID_ARGUMENTS,
    TOOL_NOT_FOUND,
    TOOL_EXECUTION_ERROR,
    MULTIPLE_MATCHES,
    TEXT_NOT_FOUND,
    INVALID_LINE_RANGE,
    STALE_EDIT_CONTEXT,
    BINARY_FILE,
    NO_EFFECT_CHANGE,
    NOT_A_REGULAR_FILE,
    WRITE_FAILED,
    PROCESS_TIMEOUT,
    PROCESS_START_FAILED,
    TEST_FAILED
}
