package com.agent.tool;

public enum ToolErrorCode {
    WORKSPACE_VIOLATION,
    FILE_NOT_FOUND,
    ACCESS_DENIED,
    INVALID_ARGUMENTS,
    INVALID_PATTERN,
    TOOL_NOT_FOUND,
    TOOL_UNAVAILABLE_IN_ENVIRONMENT,
    TOOL_EXECUTION_ERROR,
    MULTIPLE_MATCHES,
    AMBIGUOUS_MATCH,
    TEXT_NOT_FOUND,
    INVALID_LINE_RANGE,
    STALE_EDIT_CONTEXT,
    REPAIR_REQUIRES_FRESH_READ,
    BINARY_FILE,
    NO_EFFECT_CHANGE,
    NOT_A_REGULAR_FILE,
    FILE_ALREADY_EXISTS,
    PARENT_DIRECTORY_NOT_FOUND,
    WRITE_FAILED,
    PROCESS_TIMEOUT,
    PROCESS_START_FAILED,
    TEST_FAILED
}
