package com.agent.agent;

public enum AgentActionType {
    PLANNING_ROUTED,
    PLAN_CREATED,
    PLAN_UPDATED,
    PLAN_STEP_UPDATE,
    REPLAN,
    PLAN_FALLBACK,
    PLAN_COMPLETION_FEEDBACK,
    TOOL_CALL,
    AUTO_REREAD,
    POST_EDIT_VERIFICATION,
    VERIFICATION_REPAIR,
    COMPLETION_GUARD,
    RUNTIME_FEEDBACK,
    FINAL_ANSWER,
    ERROR
}
