package com.agent;

public enum RoutingReason {
    EXPLICIT_MUTATION_TARGET,
    EXPLICIT_FILE_CREATION,
    FILE_DISCOVERY_REQUEST,
    WORKSPACE_READ_REQUEST,
    AMBIGUOUS_WORKSPACE_REQUEST,
    INCOMPLETE_CONTEXTUAL_REQUEST,
    GENERAL_KNOWLEDGE
}
